[versions]
kotlin = "1.6.21"
ksp = "1.6.21-1.0.6"
kotlinpoet = "1.12.0"

[libraries]
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

[plugins]
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }